name: Dinosaurs Eat Everybody
description: For all your Dave Schwantes related needs.
url: http://dinosaurseateverybody.com/blog
markdown: redcarpet
pygments: true
permalink: /:title
baseurl: /blog/
paginate: 10
paginate_path: /page:num
comments: true
